# Generated by Django 3.2.7 on 2021-09-28 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='title of msg', max_length=255)),
                ('message', models.TextField(help_text='add message')),
            ],
        ),
    ]
